travis:
  secure:
    BINSTAR_TOKEN: YxnbMv7aIjngMMMSrxAsiqdwuEtQIFEz6RdnZR/N3Frpk3ui5I5AB8V4MfqGBozmfomTMlClG0ylYicBAJoJsiXZV8yecFR5Co8i12k+wiueWQG7KdO/I6/8Ya38TOBFYtYVcJONz5PJS7Iqjm1svtSQ1y2R9t1xs6x4a59F6oTfIrLgwIzGUUSql3q2iil+0Wimgfi0NVGz/Ahs1qXWl/SHibbFL/o3kHuM4ciajoDNueBIGFKUmg8jIySPN4Jh0wvbEdXqOLegRCwRMHVDWsEVkeWDHn1cngQhklIAoHyBk+s/tk3Gcdh7nlzLBt0H+37EwwDWT12RzSGzEg7XbnhLYJPtHQijS4ppO8C81D5cJoYBl/SR736Q0bqdMCl5SqYwBsnY3YMr28xLn2pps4kB4alpm/DU2u6Lf67IuSDiltkbWFLcivZKQtYTA1zKsY3+/YoQD9Y+p8lsdzFJXCVfYfFgRK0WNu/z6761cudm/jaa0AjDinSH4oFLL5lFlUdyNe0PL4bN9gXfoFZhn5W15Ang/pBWybdoyzgDVEh03+dRvTfaRBHQB8SNZy32EzBmjNHXb+Ywtqi9Y7UW09/mqWSOP4t6HpCc1YS2Dsre5cZRoEzhBRZflshHoxnbl/o/F9zA3qxDw7ccLgUVRfROTCK+g29W73+adbe54jw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
